---
abstract: 'Run-time properties on scalar variables'
author:
  - 'Marcel Gruenauer <marcel@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Scalar-Properties
provides:
  Scalar::Properties:
    file: lib/Scalar/Properties.pm
    version: 1.100860
requires:
  Carp: 0
  English: 0
  File::Find: 0
  File::Temp: 0
  Scalar::Util: 0
  Test::More: 0.88
  overload: 0
  perl: 5.008
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Scalar-Properties
  homepage: http://search.cpan.org/dist/Scalar-Properties/
  repository: http://github.com/hanekomu/Scalar-Properties
version: 1.100860
